#!/usr/bin/env bash
# installing and updating engine X
sudo apt-get -y update && sudo apt-get -y install nginx
sudo echo 'Holberton School' > /var/www/html/index.html
# Redirection to Nyan Cat
sudo service nginx start
sudo sed -i "s|server_name\ _;|\trewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;|" /etc/nginx/sites-available/default
