#!/usr/bin/env bash
# installing and updating engine X
sudo apt-get -y update && sudo apt-get -y install nginx
sudo echo 'Holberton School' > /var/www/html/index.html
# Redirection to Nyan Cat
sudo sed -i '37i\$redirect' /etc/nginx/sites-available/default
redirect="server_name nomadengineers.tech;rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo service nginx start
