#!/usr/bin/env bash
# This script also displays "Holberton School" 10 times
# but
# displays bad luck for the 4th loop iteration
# displays good luck for the 8th loop iteration
# displays Holberton School for the other iterations
index=0
while (( index < 10 ));
do
    if (( index == 3 ));
    then
        echo "bad luck"

    elif (( index == 7 ));
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
  ((index++))
done