#!/usr/bin/env bash
# this container so that Nginx is running as the nginx user.
sudo pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx nginx
sudo -u nginx service nginx restart
