#!/usr/bin/env bash
# 7 lines or less
sudo pkill apache2
sudo chmod 777 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo -u nginx nginx
sudo -u nginx service nginx restart
